baseURL = 'https://www.destiny-matrix.com'
languageCode = 'en-us'
title = 'InSight'
copyright = 'Copyright 2023 InSight. All rights reserved.'
theme = 'diary'

[[menu.main]]
name = 'About'
url = '/about/about'
weight = 0

[[menu.main]]
name = 'Categories'
url = '/Categories'
weight = 1