baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'InSight'
theme = 'diary'

[[menu.main]]
name = 'About'
url = '/about/about'
weight = 0

[[menu.main]]
name = 'Categories'
url = '/Categories'
weight = 1